name: flutter_rider_locator
description: "A Flutter package to simulate rider and nearby stores/customers in a 10km range."
version: 1.0.2+3

# author: Munlika Chaipradit
homepage: https://github.com/munlikaCh/flutter_rider_locator
# publish_to: "none" # ไม่ต้องการเผยแพร่ไปที่ pub.dev

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_lints: ^5.0.0
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.5.11
  geolocator: ^13.0.3
  google_directions_api: ^0.10.0
  http: ^1.1.0
  flutter_polyline_points: ^2.1.0
  location:  ^8.0.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^5.0.0

# dependency_overrides:
#   google_maps_flutter_web: ^0.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
